"""
src/app_modules — 主应用解耦子模块包
"""

from src.app_modules.bootstrap import (
    _alert_group_for_account,
    _command_listeners,
    _has_configured_workload,
    _health_check,
    _init_accounts,
    _initial_admin_banner,
    _install_stop_handlers,
    _last_command_status,
    _message_monitor_enabled,
    _on_config_reload,
    _required_account_ids,
    _sync_command_listeners,
    _valid_monitors,
    get_command_listeners,
    get_main_loop,
    handle_openid_action,
    handle_test_push,
    set_main_loop,
)
from src.app_modules.daily_summary import (
    DISK_WARN_BYTES,
    SUMMARY_MAX_ATTEMPTS,
    SUMMARY_RETRY_SECONDS,
    _build_daily_summary,
    _daily_summary_loop,
    _dir_size,
    _get_jst_now,
    _send_summary_with_retry,
    _storage_line,
    _to_jst_date,
)
from src.app_modules.message_worker import (
    _MemberCycleResult,
    _calc_sleep_seconds,
    _message_cycle_summary,
    _next_interval,
    _run_cycle,
    _run_loop,
    _wait_or_trigger,
)
from src.app_modules.process_lock import (
    PID_FILE,
    STOP_FILE,
    _acquire_instance_lock,
    _is_pid_running,
    _is_python_process,
    _kill_pid,
    _stop_requested,
)

__all__ = [
    # process_lock
    "PID_FILE",
    "STOP_FILE",
    "_is_pid_running",
    "_is_python_process",
    "_kill_pid",
    "_acquire_instance_lock",
    "_stop_requested",
    # daily_summary
    "DISK_WARN_BYTES",
    "SUMMARY_MAX_ATTEMPTS",
    "SUMMARY_RETRY_SECONDS",
    "_get_jst_now",
    "_to_jst_date",
    "_dir_size",
    "_storage_line",
    "_build_daily_summary",
    "_send_summary_with_retry",
    "_daily_summary_loop",
    # message_worker
    "_MemberCycleResult",
    "_message_cycle_summary",
    "_calc_sleep_seconds",
    "_next_interval",
    "_wait_or_trigger",
    "_run_cycle",
    "_run_loop",
    # bootstrap
    "_message_monitor_enabled",
    "_valid_monitors",
    "_required_account_ids",
    "_has_configured_workload",
    "_initial_admin_banner",
    "_alert_group_for_account",
    "_health_check",
    "_install_stop_handlers",
    "_init_accounts",
    "_command_listeners",
    "_last_command_status",
    "set_main_loop",
    "get_main_loop",
    "get_command_listeners",
    "_sync_command_listeners",
    "_on_config_reload",
    "handle_test_push",
    "handle_openid_action",
]
